FROM nginx:alpine
RUN apk add --no-cache openssl
COPY . /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY start.sh /start.sh
RUN chmod +x /start.sh
EXPOSE 80 443
CMD ["/start.sh"]
